### ISSUE TITLE
Coordinate dependency on all modules and izero with new terraform-ibm-container-platform

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/planning#704] opened 2021-02-10 23:44 UTC
A new version of the terraform-ibm-container-platform is not compatible with older versions of the upstream terraform modules that we include in the cli-tools image.

https://github.com/ibm-garage-cloud/terraform-ibm-container-platform/compare/v1.20.6...v1.20.7

The new version 1.20.7 uses `name` as the cluster name, and old versions of the upstream is not compatible

The terraform will fail like this
```
Error: Missing required argument

  on .terraform/modules/dev_cluster/main-1-vpc.tf line 107, in data "ibm_container_vpc_cluster" "config":
 107: data "ibm_container_vpc_cluster" "config" {

The argument "cluster_name_id" is required, but no definition was found.


Error: Unsupported argument

  on .terraform/modules/dev_cluster/main-1-vpc.tf line 111, in data "ibm_container_vpc_cluster" "config":
 111:   name              = local.cluster_name

An argument named "name" is not expected here.
```

We need to update all the github actions to use the newer version of the image 0.10.0-lite

https://github.com/ibm-garage-cloud/ibm-garage-cli-tools/compare/v0.9.0-lite...v0.10.0-lite

Actions Items

- [ ] Update all terraform modules to use new version like this https://github.com/ibm-garage-cloud/terraform-tools-artifactory/blob/main/.github/workflows/verify.yaml#L16 `quay.io/ibmgaragecloud/cli-tools:v0.10.0-lite`
- [ ] Update Iteration zero to new version of ibm-garage-cloud/terraform-ibm-container-platform, at the same time update the launch.sh and quick install
- https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/blob/master/terraform/stages/stage1-cluster.tf#L2
- https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/blob/master/terraform/stages-cluster/stage1-cluster.tf#L2
- https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/blob/master/install/install-ibm-toolkit.yaml#L44
- https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero/blob/master/launch.sh#L8
-

**Comment by seansund** [comment] 2021-02-11 01:40
This issue is caused by a back level version of the IBM Cloud terraform provider. I'll update the cli-tools image version in iteration zero and it should be fixed

**Closed** 2021-03-08 16:19 UTC
Labels: terraform
