### ISSUE TITLE
Enable code patterns with Jenkins as previously enabled with Tekton works fine - OCP 43

### ISSUE THREAD

**Issue by balasgit** [ibm-garage-cloud/planning#256] opened 2020-04-03 14:32 UTC
**Describe the bug**
 Code Pattern was working fine with Tekton. Reenable code pattern with Jenkins pipeline in the same workspace and tried to run but it gives 

**To Reproduce**
Enable the code pattern with Tekton and make it work.
Enable the code pattern with Jenkins and you will see this issue

**Expected behavior**
Jenkins pipeline should work.

**Screenshots**
balas-mbp:ocp4-aus-cp1 bala$ igc pipeline -n dev-aus1 --jenkins
Creating pipeline on openshift cluster
Creating secret(s) with git credentials
  Project git repo: https://github.com/gsi-enablement-one/ocp4-aus-cp1.git
? Provide the username: balasgit
? Provide your password/personal access token: [hidden]
? Provide the branch the pipeline should use: master
Registering pipeline: gsi-enablement-one.ocp4-aus-cp1
Creating git webhook
Creating webhook to url:  undefined/github-webhook/
Error registering pipeline: Cannot read property 'jenkinsUrl' of undefined

**IBM Cloud**
Select the services and tools affected

- [ ] IBM Kubernetes Service Managed Service
- [X ] Red Hat OpenShift Managed Services
- [X ] Jenkins
- [ ] Tekton
- [ ] SonarQube
- [ ] Pact
- [ ] Artifactory
- [ ] IBM Image Registry

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  MacOS
 - Browser [e.g. chrome, safari] CLI 

**Additional context**
 Thoughts -- Do I need to reenable the whole project with jenkins
     igc namespace dev-jg --jenkins 

 If i do, then it will overwrite my changes in the local workspace which am trying to test something (Jenkins file)

**Comment by balasgit** [comment] 2020-04-03 14:44
Workaround for the above issue

1. New Space with Jenkins enabled
2. Rerun the Pipeline with Jenkins which works 

I want to quickly test jenkins fix so taking this workaround approach

**Comment by csantanapr** [comment] 2020-04-03 15:03
I would say you found a problem trying to enable a single namespace with both jenkins, and tekton.

I can see a single OCP43 cluster with multiple namespaces, each namespace having jenkins or tekton but not both.

Wondering if that would be a real life use cases, where a team would use both on the same namespace, and if it's worth supporting it.

**Comment by balasgit** [comment] 2020-04-03 15:11
I can move forward with the separate workspace for the Jenkins.

May be we can collaborate in Catalyst Office hours  and decide if there are any use-cases from customer perspective 

we can decide accordingly.

**Comment by seansund** [comment] 2020-04-06 15:24
run `igc namespace {name} --jenkins`

**Comment by seansund** [comment] 2020-04-06 15:24
duplicate of #257

**Comment by balasgit** [comment] 2020-04-06 16:07
Just curious -- Does any of the files in the local laptop will have reference to new namespace after i run the cmd run igc namespace {name} --jenkins ?

I am interested to know which are all files gets impacted whenever i enable with new namespace.

**Closed** 2020-06-01 22:09 UTC
Labels: bug
